version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carumba_dev
    volumes:
      - dbdata:/var/lib/postgresql/data
    command: -p ${DATABASE_PORT:-5433}
    ports:
      - 5433:5433

  app:
    image: "hexpm/elixir:1.17.1-erlang-27.0-debian-bullseye-20240701-slim"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      POSTGRES_HOST: "db"
    command: >
      sh -c "
        apt-get update -y && apt-get install -y build-essential git
        apt-get clean
        dpkg --configure -a
        rm -f /var/lib/apt/lists/*_*
        mix local.hex --force &&
        mix local.rebar --force &&
        mix deps.get &&
        mix ecto.migrate &&
        mix ecto.setup &&
        exec mix phx.server
      "
    ports:
      - 4000:4000

volumes:
  dbdata: