defmodule Carumba.Repo.Migrations.AlterValueFromStringToMap do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:questions) do
      add :type, :text, null: false, default: "text"
    end

    alter table(:answers) do
      remove :value
      add :value, :map
    end
  end

  def down do
    alter table(:answers) do
      remove :value
      add :value, :text
    end

    alter table(:questions) do
      remove :type
    end
  end
end
