defmodule Carumba.Repo.Migrations.AddAnswers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:answers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :value, :text

      add :form_id,
          references(:forms,
            column: :id,
            name: "answers_form_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :question_id,
          references(:questions,
            column: :id,
            name: "answers_question_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:answers, "answers_form_id_fkey")

    drop constraint(:answers, "answers_question_id_fkey")

    drop table(:answers)
  end
end
