defmodule Carumba.Repo.Migrations.CreateDocuments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:documents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :form_id,
          references(:forms,
            column: :id,
            name: "documents_form_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    rename table(:answers), :form_id, to: :document_id

    drop constraint(:answers, "answers_form_id_fkey")

    alter table(:answers) do
      modify :document_id,
             references(:documents,
               column: :id,
               name: "answers_document_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    execute("ALTER TABLE answers alter CONSTRAINT answers_document_id_fkey NOT DEFERRABLE")
  end

  def down do
    drop constraint(:answers, "answers_document_id_fkey")

    alter table(:answers) do
      modify :form_id,
             references(:forms,
               column: :id,
               name: "answers_form_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    rename table(:answers), :document_id, to: :form_id

    drop constraint(:documents, "documents_form_id_fkey")

    drop table(:documents)
  end
end
