defmodule Carumba.Repo.Migrations.AddSubFormToQuestions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:questions) do
      add :sub_form_id,
          references(:forms,
            column: :id,
            name: "questions_sub_form_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:questions, "questions_sub_form_id_fkey")

    alter table(:questions) do
      remove :sub_form_id
    end
  end
end
