defmodule Carumba.Repo.Migrations.AlterQuestionReferenceToSlug do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:answers, "answers_question_id_fkey")

    alter table(:answers) do
      modify :question_id,
             references(:questions,
               column: :slug,
               name: "answers_question_id_fkey",
               type: :text,
               prefix: "public"
             )
    end

    execute("ALTER TABLE answers alter CONSTRAINT answers_question_id_fkey NOT DEFERRABLE")
  end

  def down do
    drop constraint(:answers, "answers_question_id_fkey")

    alter table(:answers) do
      modify :question_id,
             references(:questions,
               column: :id,
               name: "answers_question_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
