defmodule Carumba.Repo.Migrations.AlterQuestionConfigurationDefaultToEmptyMap do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:questions) do
      modify :configuration, :map, default: %{}
    end
  end

  def down do
    alter table(:questions) do
      modify :configuration, :map, default: nil
    end
  end
end
