defmodule Carumba.Repo.Migrations.InitialSetup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:questions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slug, :text
    end

    create table(:forms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slug, :text
    end

    create table(:form_questions, primary_key: false) do
      add :form_id,
          references(:forms,
            column: :id,
            name: "form_questions_form_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :question_id,
          references(:questions,
            column: :id,
            name: "form_questions_question_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:form_questions, "form_questions_form_id_fkey")

    drop constraint(:form_questions, "form_questions_question_id_fkey")

    drop table(:form_questions)

    drop table(:forms)

    drop table(:questions)
  end
end
