defmodule Carumba.Repo.Migrations.AddReferencesToQuestions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:questions, "questions_sub_form_id_fkey")

    alter table(:questions) do
      modify :sub_form_id,
             references(:forms,
               column: :id,
               name: "questions_sub_form_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    execute("ALTER TABLE questions alter CONSTRAINT questions_sub_form_id_fkey NOT DEFERRABLE")
  end

  def down do
    drop constraint(:questions, "questions_sub_form_id_fkey")

    alter table(:questions) do
      modify :sub_form_id,
             references(:forms,
               column: :id,
               name: "questions_sub_form_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
