defmodule Carumba.Repo.Migrations.UpdateQuestionFieldsAndAddConfiguration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:questions), :is_required, to: :is_required?

    alter table(:questions) do
      modify :is_required?, :boolean
      add :configuration, :map
    end
  end

  def down do
    alter table(:questions) do
      remove :configuration
      modify :is_required, :boolean
    end

    rename table(:questions), :is_required?, to: :is_required
  end
end
